CREATE TABLE article (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id)
)
ENGINE = InnoDB CHARACTER SET = utf8mb4
COMMENT '文章';

CREATE TABLE article_tag (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    article_id BIGINT UNSIGNED NOT NULL,
    tag_id BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
)
ENGINE = InnoDB CHARACTER SET = utf8mb4
COMMENT '文章和标签关联';

CREATE TABLE tag (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id)
)
ENGINE = InnoDB CHARACTER SET = utf8mb4
COMMENT '标签';
